### ISSUE TITLE
Datasets and effectiveness

### ISSUE THREAD

**Issue by Mary-Mary** [jhlau/online_twitter_lda#2]
Hello!
I have a question. In your article you write that you use document-level annotations and find the effectiveness of the model by calculating the “tweet”-level precision, recall and F-score.  Can you give me a file of annotating documents and tell me about the mechanism of using annotating documents and calculating F-score using your codes? How did you calculate F-score?

**Comment by jhlau** [comment]
A document is a tweet. So we are computing F-score using standard precision and recall definitions (we used equal weighting of precision and recall).

Say there are 5 new documents/tweets to be classified:
A, B, C, D, E

True novel documents: A, B, D
Predicted novel documents: B, C
Precision = 1/2
Recall = 1/3
F-score = (2*1/2*1/3) / (1/2+1/3)
