### ISSUE TITLE
Document-topic distribution?

### ISSUE THREAD

**Issue by bwang482** [jhlau/online_twitter_lda#3]
Hi there,

Can I ask how do I have the LDA document-topic distribution please? Where (if possible) in lda.py that generates such document-topic distribution? 

Thanks!

Bo

**Comment by jhlau** [comment]
Hi, unfortunately the code doesn't print document-topic distribution, but the information is all contained in self.n_m_z of the lda class, so you can just load the model and look at that variable.

**Comment by bwang482** [comment]
Thanks. Hmm, is self.n_m_z not summed to one as probability distribution over topics? I have for example:

> In [95]: model[1].n_m_z[3467]
> Out[95]: 
> array([  1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   **6.00100000e+00**,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03,   1.00000000e-03,   1.00000000e-03,
>          1.00000000e-03])

Just wondering if this is normal or have I made a mistake somewhere during the learning.

**Comment by jhlau** [comment]
It's the raw count + smoothing prior (\alpha). So if you want to convert to probability distribution, you just need to get the sum and divide the elements by the sum.
